### ISSUE TITLE
Run the assistant flow locally(Step 3) in Readme fail 

### ISSUE THREAD

**Issue by LianwMS** [Azure-Samples/assistant-data-openai-python-promptflow#18]
(.venv) PS D:\aigallery\assistant-data-openai-python-promptflow> pf flow test --flow ./src/copilot_sdk_flow/flow.flex.yaml --inputs question="which month has peak sales in 2023"
Starting prompt flow service...
Start prompt flow service on port 23333, version: 1.10.0.
You can stop the prompt flow service with the following command:'pf service stop'.
Alternatively, if no requests are made within 1 hours, it will automatically stop.
D:\aigallery\assistant-data-openai-python-promptflow\.env
You can view the trace detail from the following URL:
http://localhost:23333/v1.0/ui/traces/?#collection=copilot_sdk_flow&uiTraceId=0x8111143c9abe27d18a90aab65f7a134b
**pf.flow.test failed with UserErrorException: Exception: Execution failure in 'flow_entry_copilot_assistants': (TypeError) flow_entry_copilot_assistants() missing 1 required positional argument: 'chat_input'**

**Comment by jfomhover** [comment]
This now works e2e
