### ISSUE TITLE
Dependency installation failed for Python 3.12

### ISSUE THREAD

**Issue by Vivihung** [Azure-Samples/assistant-data-openai-python-promptflow#41]
### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
1. Install the [latest Python 3.12.3](https://www.python.org/downloads/)
2. Install the Python dependency `pip install -r .\src\requirements.txt`

### Any log messages given by the failure
Got error `ModuleNotFoundError: No module named 'imp'`
![image](https://github.com/Azure-Samples/assistant-data-openai-python-promptflow/assets/4814277/7ada476b-b0f9-4db6-87a6-a2cf113aa64a)

### Expected/desired behavior
Per [this ](https://stackoverflow.com/questions/77401730/modulenotfounderror-no-module-named-imp)discussion, `imp` seems being deprecated after Python 3.11+. Recommend to change the prerequisite to Python 3.10 (not Python 3.10 above) in README.

### OS and Version?
> Windows 11 (PowerShell)

**Comment by jfomhover** [comment]
Thank you for reporting this, I'll specify the requirements to strictly python 3.10 for now.
