### ISSUE TITLE
Template Testing

### ISSUE THREAD

**Issue by kristenwomack** [Azure-Samples/assistant-data-openai-python-promptflow#56]
- [ ] Testing works following the Readme, Codespaces is the priority
- [ ]  Make sure azd works in Codespaces (flag to fix if not)
- [ ]  We have verification step in README after the resources are deployed, there is a description of what the customer needs to do next
- [x]  Ensure managed identity is implemented and working
- [ ]  If local doesn't work, we need a note in the README (make this explicit)

Nice to have (but document if not working)
- [ ] runs local

Must have two testers approval, minimum.

**Comment by marlenezw** [comment]
This one was on the list @kristenwomack but I don't think it's ready to be added. Still needs azd added...in code spaces azd up doesn't work yet. We can circle back probably post-build

**Comment by kristenwomack** [comment]
> This one was on the list @kristenwomack but I don't think it's ready to be added. Still needs azd added...in code spaces azd up doesn't work yet. We can circle back probably post-build

Noted, thank you @marlenezw
